version: '2.3'
services:
  web:
    build: .
    ports:
    - '127.0.0.1:8888:80'
    volumes:
    - './LocalSettings.php:/var/www/html/LocalSettings.php:ro'
    - './html/cache:/var/www/html/cache'
    - './html/images:/var/www/html/images'
    - './html/sitemap:/var/www/html/sitemap:ro'
    - './html/favicon.ico:/var/www/html/favicon.ico:ro'
    - './html/robots.txt:/var/www/html/robots.txt:ro'
    restart: unless-stopped
  cron:
    build: .
    command: /usr/sbin/cron -f
    volumes:
    - './LocalSettings.php:/var/www/html/LocalSettings.php:ro'
    - './html/cache:/var/www/html/cache'
    - './html/images:/var/www/html/images'
    - './html/sitemap:/var/www/html/sitemap'
    - './html/favicon.ico:/var/www/html/favicon.ico:ro'
    - './html/robots.txt:/var/www/html/robots.txt:ro'
    restart: unless-stopped
