version: '2.3'
services:
  web:
    build:
      context: .
      args:
      - http_proxy
      - https_proxy
      - no_proxy
    ports:
    - '127.0.0.1:8080:80'
    volumes:
    - './LocalSettings.php:/var/www/html/LocalSettings.php:ro'
    - './html/cache:/var/www/html/cache'
    - './html/images:/var/www/html/images'
    - './html/sitemap:/var/www/html/sitemap:ro'
    init: true
    restart: always
  cron:
    build: .
    command: /usr/sbin/cron -f
    volumes:
    - './LocalSettings.php:/var/www/html/LocalSettings.php:ro'
    - './html/cache:/var/www/html/cache'
    - './html/images:/var/www/html/images'
    - './html/sitemap:/var/www/html/sitemap'
    init: true
    restart: always
