# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-1.6.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-05-09T19:42:34Z"
  labels:
    app: nlpub
  name: nlpub
spec:
  containers:
  - command:
    - /usr/sbin/cron
    - -f
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
      value: nlpub
    - name: container
      value: podman
    - name: MEDIAWIKI_VERSION
      value: 1.34.1
    - name: MEDIAWIKI_SHA512
      value: 3a03ac696e2d5300faba0819ba0d876a21798c8dcdc64cc2792c6db0aa81d4feaced8dc133b6ca3e476c770bf51516b0a624cb336784ae3d2b51c8c0aa5987a0
    - name: PHP_ASC_URL
      value: https://www.php.net/distributions/php-7.3.17.tar.xz.asc
    - name: APACHE_CONFDIR
      value: /etc/apache2
    - name: PHP_EXTRA_BUILD_DEPS
      value: apache2-dev
    - name: PHP_EXTRA_CONFIGURE_ARGS
      value: --with-apxs2 --disable-cgi
    - name: GPG_KEYS
      value: CBAF69F173A0FEA4B537F470D66C9593118BCCB6 F38252826ACD957EF380D39F2F7956BC5DA04B5D
    - name: PHP_CPPFLAGS
      value: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
    - name: PHP_LDFLAGS
      value: -Wl,-O1 -pie
    - name: PHP_MD5
    - name: PHP_CFLAGS
      value: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
    - name: PHP_INI_DIR
      value: /usr/local/etc/php
    - name: APACHE_ENVVARS
      value: /etc/apache2/envvars
    - name: PHP_VERSION
      value: 7.3.17
    - name: PHP_URL
      value: https://www.php.net/distributions/php-7.3.17.tar.xz
    - name: PHP_SHA256
      value: 6a30304c27f7e7a94538f5ffec599f600ee93aedbbecad8aa4f8bec539b10ad8
    - name: MEDIAWIKI_MAJOR_VERSION
      value: "1.34"
    - name: MEDIAWIKI_BRANCH
      value: REL1_34
    - name: PHPIZE_DEPS
      value: "autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake
        \t\tpkg-config \t\tre2c"
    image: localhost/nlpub:latest
    restartPolicy: Always
    name: nlpub_cron
    ports:
    - containerPort: 80
      hostIP: 127.0.0.1
      hostPort: 8888
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    volumeMounts:
    - mountPath: /var/www/html/favicon.ico
      name: srv-nlpub-html-favicon.ico
      readOnly: true
    - mountPath: /var/www/html/robots.txt
      name: srv-nlpub-html-robots.txt
      readOnly: true
    - mountPath: /var/www/html/cache
      name: srv-nlpub-html-cache
    - mountPath: /var/www/html/images
      name: srv-nlpub-html-images
    - mountPath: /var/www/html/sitemap
      name: srv-nlpub-html-sitemap
    - mountPath: /var/www/html/LocalSettings.php
      name: srv-nlpub-LocalSettings.php
      readOnly: true
    workingDir: /var/www/html
  - command:
    - /bin/sh
    - -c
    - apache2-foreground
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
      value: nlpub
    - name: container
      value: podman
    - name: PHP_SHA256
      value: 6a30304c27f7e7a94538f5ffec599f600ee93aedbbecad8aa4f8bec539b10ad8
    - name: PHP_MD5
    - name: PHP_LDFLAGS
      value: -Wl,-O1 -pie
    - name: GPG_KEYS
      value: CBAF69F173A0FEA4B537F470D66C9593118BCCB6 F38252826ACD957EF380D39F2F7956BC5DA04B5D
    - name: MEDIAWIKI_BRANCH
      value: REL1_34
    - name: MEDIAWIKI_SHA512
      value: 3a03ac696e2d5300faba0819ba0d876a21798c8dcdc64cc2792c6db0aa81d4feaced8dc133b6ca3e476c770bf51516b0a624cb336784ae3d2b51c8c0aa5987a0
    - name: PHP_CFLAGS
      value: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
    - name: PHP_VERSION
      value: 7.3.17
    - name: PHP_URL
      value: https://www.php.net/distributions/php-7.3.17.tar.xz
    - name: PHP_ASC_URL
      value: https://www.php.net/distributions/php-7.3.17.tar.xz.asc
    - name: PHP_CPPFLAGS
      value: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
    - name: PHPIZE_DEPS
      value: "autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake
        \t\tpkg-config \t\tre2c"
    - name: PHP_INI_DIR
      value: /usr/local/etc/php
    - name: APACHE_CONFDIR
      value: /etc/apache2
    - name: APACHE_ENVVARS
      value: /etc/apache2/envvars
    - name: PHP_EXTRA_BUILD_DEPS
      value: apache2-dev
    - name: PHP_EXTRA_CONFIGURE_ARGS
      value: --with-apxs2 --disable-cgi
    - name: MEDIAWIKI_MAJOR_VERSION
      value: "1.34"
    - name: MEDIAWIKI_VERSION
      value: 1.34.1
    image: localhost/nlpub:latest
    restartPolicy: Always
    name: nlpub_web
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    volumeMounts:
    - mountPath: /var/www/html/robots.txt
      name: srv-nlpub-html-robots.txt
      readOnly: true
    - mountPath: /var/www/html/cache
      name: srv-nlpub-html-cache
    - mountPath: /var/www/html/images
      name: srv-nlpub-html-images
    - mountPath: /var/www/html/sitemap
      name: srv-nlpub-html-sitemap
      readOnly: true
    - mountPath: /var/www/html/LocalSettings.php
      name: srv-nlpub-LocalSettings.php
      readOnly: true
    - mountPath: /var/www/html/favicon.ico
      name: srv-nlpub-html-favicon.ico
      readOnly: true
    workingDir: /var/www/html
  volumes:
  - hostPath:
      path: /srv/nlpub/html/favicon.ico
      type: File
    name: srv-nlpub-html-favicon.ico
  - hostPath:
      path: /srv/nlpub/html/robots.txt
      type: File
    name: srv-nlpub-html-robots.txt
  - hostPath:
      path: /srv/nlpub/html/cache
      type: Directory
    name: srv-nlpub-html-cache
  - hostPath:
      path: /srv/nlpub/html/images
      type: Directory
    name: srv-nlpub-html-images
  - hostPath:
      path: /srv/nlpub/html/sitemap
      type: Directory
    name: srv-nlpub-html-sitemap
  - hostPath:
      path: /srv/nlpub/LocalSettings.php
      type: File
    name: srv-nlpub-LocalSettings.php
status: {}

